---
layout: cv
title: Lydia Hammer's CV
---
# Lydia Hammer
Student, Accountant, Business Analyst.

<div id="webaddress">
<a href="lydnsutton@gmail.com">lydnsutton@gmail.com</a>
| <a href="https://www.linkedin.com/in/lydiahammer-/">My LinkedIn</a>
<!-- | <a href="https://lydiahammer.github.io/datascience_portfolio/gh-pages/resume.pdf">Download PDF</a> -->
| <a href="https://github.com/byuidatascience/datascience_portfolio/blob/gh-pages/resume.pdf">Download PDF</a>
</div>


## Currently

A Business Analytics & Accounting Student at BYU-Idaho.

### Specialized in

Excel, SQL, Python, R, Power BI, various tax softwares, Quickbooks

### Interests

Busniess analytics, accounting, consulting, operations, business management, finance


## Education

`Sep 2024 - current`
__Brigham Young University Idaho__

- Bachelors Degree

`Aug 2021 - May 2024`
__Utah Valley University__

- Associates Degree

`Aug 2021 - May 2024`
__Salem Hills High School__




## Awards

`2026`
Bronze & Silver Career Success Certification, BYU-Idaho



## Projects

`2025`
Webinar Attendance Analysis - consulting project done with R and Excel for a small business

`2025`
Churn Analysis Dashboard - analysis project done in Excel for a small business



## Occupation

`Sep 2025 - current`
__Associate Accountant__, Miskin & Associates

- Prepared clients tax documents
- Assisted with bookkeeping and financial reconciliation
- Created a Break Even Analysis report for a client

`Aug 2021 - Apr 2025`
__Administrative Assistant__, Vyde Tax & Accounting

- Assisted with bookkeeping and data entry
- Completed 500+ BOI reports for clients

<!-- ### Footer

Last updated: May 2013 -->